### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by katajakasa** [kode54/dumb#11]
Would it be possible to get a release tagged out ? Possibly dumb 0.9.4 or 1.0 or something ? That would make it easier to refer to the project and maybe package it for linux.

**Comment by kode54** [comment]
I have decided to call it 1.0, since it's quite a major difference from 0.9.3 or whatever the last stable release was. I'll have to think of good times to tag it in the future.

**Comment by katajakasa** [comment]
Nice! We can start referring to an actual version in openomf project, and maybe I could even poke at the debian guys to start packaging a newer version.

Thanks!
