### ISSUE TITLE
Where are executables?

### ISSUE THREAD

**Issue by nemysis** [kode54/dumb#16]
In old dumb 0.93 I have had executables

```\n
/usr/bin/dumb2wav
/usr/bin/dumbout
/usr/bin/dumbplay
```

And now are only

```\n
Linking C static library libdumb.a

cmake/libdumb.a
```

How to build in?

```
dumb/src
```

```\n
dumb/src/ > make
make: *** No targets specified and no makefile found.  Stop.
```

Please make these executables and

```
cmake/libdumb.so
```

**Comment by katajakasa** [comment]
For building shared libs with cmake, take a look at https://github.com/kode54/dumb/blob/master/dumb/cmake/readme.txt .and read the BUILD_SHARED_LIBS part.

The example binaries are not included at all in this repository, as far as I know.

**Comment by kode54** [comment]
I will probably change that and re-add the example binaries, once I find the source again. Probably need minimal changes from the originals. For instance, I'd make them use the read any or load any functions, which perform intelligent detection before firing off an actual reader.

**Comment by katajakasa** [comment]
@nemysis I added new dumbout and dumbplay examples, and @kode54 merged them. Not sure if dumb2wav is necessary :/

**Comment by nemysis** [comment]
Thanks for adding dumbout and dumbplay examples. I make now openSUSE RPM for dumb and have make libargtable2 openSUSE RPM

https://build.opensuse.org/package/show/games/libargtable2
