### ISSUE TITLE
Unable to play certain .mod file

### ISSUE THREAD

**Issue by raspi** [kode54/dumb#17]
When using "Use playptmod or modplay" DUMB can't go pass 0:19 of this song. Disabling "Use playptmod or modplay" fixes issue. 

Upstream issue?

ftp://modland.ziphoid.com/pub/modules/Protracker/Nightlight/dirt.mod
http://janeway.exotica.org.uk/release.php?id=32999#downloads
https://www.dropbox.com/s/6ahm17y6oyxtgln/DIRT.MOD?dl=0

**Comment by raspi** [comment]
DUMB version 1.0.157

**Comment by raspi** [comment]
Moved to https://github.com/kode54/foo_dumb/issues/8

**Comment by kode54** [comment]
Yes, technically this is an issue with playptmod, not DUMB, and not specifically foo_dumb.
