### ISSUE TITLE
No allegro libraries

### ISSUE THREAD

**Issue by rogerbraun** [kode54/dumb#21]
Looks like the allegro libraries are gone. Are they not longer supported?

**Comment by kode54** [comment]
I never added or removed them, I guess I forgot to include something? Anyone is welcome to try maintaining them, or adding them via a fork and pull request.

**Comment by rogerbraun** [comment]
Thanks for the info, I'll look into it.

Another question, is this the official main version of dumb now? Are you the current maintainer?

**Comment by Rondom** [comment]
There is only one version of libdumb that is still maintained, which is this one and this fork has been endorsed by the original author. See http://dumb.sourceforge.net/

I think, right now the following things need to be done to make this look more "official".
* get it tested with Allegro again
* update examples, documentation
* do some proper versioned release
* have some small homepage (probably talk with the original maintainer to reuse some content and redirect people)

**Comment by winterheart** [comment]
Allegro5 has own support for dumb. Since they targeted for dumb 0.9.3, I think allegro support on dumb side is obsoleted.

**Comment by Rondom** [comment]
If we did not totally break the API, it should work in Allegro 5.
For Allegro 4, the Allegro-specific header aldumb.h is no longer shipped. Allegro 4 (and especially the games using it) are not going to disappear any time soon.

**Comment by winterheart** [comment]
Well, I'm working on return allegro support back, but there API mismatch, and I can't figure out what I need.
@kode54, can you explain, what is restrict_ parameter from dumb_read_mod_quick(DUMBFILE *f, int restrict_) (https://github.com/kode54/dumb/blob/master/dumb/src/it/readmod.c#L618)?

**Comment by tobihan** [comment]
There is a comment in dumb.h. restrict_ = 2 should be the old behavior.
https://github.com/kode54/dumb/blob/4e0faec2b81698376b78c4715d633de23140cd10/dumb/include/dumb.h#L392

**Comment by winterheart** [comment]
@tobihan thanks for hint. 
I create pr for allegro4 support. If anyone have projects with dumb+allegro4, please, can you test it?

**Comment by akien-mga** [comment]
I guess this is fixed?

**Comment by Rondom** [comment]
I think the only thing missing is someone confirming with an Allegro4-game that this works.
I cannot remember if I tried.

**Comment by akien-mga** [comment]
I've just tested against the libre game B.A.L.L.Z., it works fine :)
https://gitlab.com/ballz/ballz

(albeit with my PRs applied, especially the one that fixes the linking of libaldmb.so).

**Comment by kode54** [comment]
This should be safe to close now, right? Let me know if everything is in order now.

**Comment by Rondom** [comment]
I think this can be closed.
