### ISSUE TITLE
Directory layout

### ISSUE THREAD

**Issue by katajakasa** [kode54/dumb#22]
Currently the project has some unnecessary directories. Some thoughts:

Firstly, there is an extra "dumb" directory at the project root; moving everything from inside it to the project root might make it easier to browse things (one less click). Also, readme and other files would be available at project root, which seems to be the usual way to do things nowadays.

Also, moving VS and CMake project files to the root would clear out some extra directories, and eg. CLion IDE likes seeing cmakelists.txt in root. Not sure if moving the vc6 project would make sense, though.

Would these changes be acceptable if I made some commits ? :)

**Comment by kode54** [comment]
Sure, just need to edit the paths in the project files first. You may also want to edit or move the gitignore files for handling the build directories, too.

**Comment by katajakasa** [comment]
Btw, is the qtcreator project still used ? It seems to be stale (doesn't compile currently).

**Comment by Rondom** [comment]
Question is also if maintenance of those project files provides enough of a benefit given that CMake can create simple project files for a variety of IDEs.
