### ISSUE TITLE
dumb plug in for fb2k v1.0.164 crash

### ISSUE THREAD

**Issue by ghf50** [kode54/dumb#34]
No matter open or add any module music, fb2k crash.
fb2k v1.3.14
[Crash Report](https://mega.nz/#!6JphQSCA!v3lGBcXlF2sack6rloeAvUZlHpFfe_wRHI4OrIjZF8M)

**Comment by kode54** [comment]
Oops. That was a terrible mistake, it crashed on any non-UMX file.

**Comment by ghf50** [comment]
Thanks for fix this!
