### ISSUE TITLE
License things

### ISSUE THREAD

**Issue by katajakasa** [kode54/dumb#46]
So, the current license has some problems. 
* Dates, versions are out of date
* The request to link back mentions "http://dumb.sf.net/", which now contains outdated version
* Term 2 says that altered versions must be marked as such... On the other hand, dumb.sf.net endorses this fork. Is this still valid ?
* Term 3 says that the license file cannot be altered in any source distribution. => license cannot be changed, even if it is outdated ? Or does this count as source distribution ?
* Term 5: I don't have a dog, do I need to get one now ? :)
* Term 6: Says that Debian or a project under GPL does not need to adhere to all of these terms... but does that mean that other distributions and project under other licenses (MIT, LGPL, etc) do ?
* Terms 4-8 are funny, but generate some trouble because this is the internet, and everyone can get sued for any reason at all :(

I'd suggest changing to some generic license, but is that doable ?

**Comment by SimonN** [comment]
I agree, a proper FLOSS license would be good. I'd recommend the MIT license: It's the most common among permissive FLOSS licenses, and allows sublicensing should that ever be necessary.

But DUMB's license doesn't allow to relicense at all. To relicense DUMB properly, you'll have to contact all copyright holders: Whoever authored a part of the code is copyright holder of that code. I assume that's the 3 authors in the old license, and everybody in the git commit messages.

It's nasty, but if the license changes at all, it should change as early as possible.

**Comment by katajakasa** [comment]
Term 8 DOES say that terms 4,5,6 are invalid directly, and that term 8 is null and void also in a roundabout way. That does seem to make it compatible with GPL... I think. We still can't edit the contents though, I think ?

**Comment by Rondom** [comment]
I think it is really not worth thinking about trying to relicense without a good reason. Given that the response to the objection that a  "custom funny license" is problematic had been reponded to with snark (referring to the Debian reference), I am not sure how successful relicensing would be.
Dumb is included in Fedora, Debian, Mageia, OpenSUSE (I think), so I do not think it is too problematic.

I think the only smaller "issue" I see, is the updating of the URL and version.

**Comment by katajakasa** [comment]
I'm closing this as changing or updating the license would probably be very hard, and if the current license is acceptable to different distributions, it's probably okay.
