### ISSUE TITLE
Compilation error on 32bit debian

### ISSUE THREAD

**Issue by katajakasa** [kode54/dumb#5]
I'm getting the following error on 32bit debian linux:

```
/home/tuomas/projects/dumb/dumb/src/it/itrender.c: In function ‘_dumb_init_sse’:
/home/tuomas/projects/dumb/dumb/src/it/itrender.c:754:5: error: inconsistent operand constraints in an ‘asm’
```

Maybe the linux default -fPIC doesn't like the CPUID code ?

**Comment by Pulfer** [comment]
Looks like this fix was partially reverted in https://github.com/kode54/dumb/commit/5b36c39238d02c7f1fa8df791ae54935830300ca

**Comment by kode54** [comment]
Sorry about that, I have fixed this. It's what I get for mixing files from different copies of the code base, where certain changes may not have been applied.
