### ISSUE TITLE
Public dumb.h unconditionally redefines MIN, MAX, MID, ABS

### ISSUE THREAD

**Issue by Rondom** [kode54/dumb#52]
Public dumb.h unconditionally redefines MIN, MAX, MID, ABS. I am wondering what the reason for this is. I think it should go under include/internal.

Or is there any reason why a user of DUMB might need those macros? If there is such a reason, they should probably be prefixed.

**Comment by SimonN** [comment]
I'd remove these macros for 2.0. They don't seem to be used within DUMB, and callers would be surprised about the redefinition.

**Comment by SimonN** [comment]
Correction: They are used inside DUMB. Thus, yes, should make them internal.

**Comment by SimonN** [comment]
@Rondom: I'm working on cleaning header defines. Among this, I'll move the above 4 macros to `internal/dumb.h`, and include that file in any `.c` that acts up.

Expect a PR within a day. :-) Everybody will be cordially invited to scrutinize.

**Comment by kode54** [comment]
I already moved them to internal, and included internal/dumb.h where they are used and it wasn't already included.

**Comment by SimonN** [comment]
Even better, thanks! Just got your commit and looks good.

**Comment by Rondom** [comment]
6e924e69701ffca777aa88bb9648af9541f53c56 fixed this.
