### ISSUE TITLE
basement.it sounds garbled (silence and short bleeps)

### ISSUE THREAD

**Issue by SimonN** [kode54/dumb#57]
File: http://www.lixgame.com/etc/basement.it -- from the soundtrack of the cancelled Jazz Jackrabbit 3. Most files of that soundtrack play perfectly in DUMB. This one file doesn't.

Issue manifests in a small Allegro 5 program that calls DUMB master (6e924e69701ffc) as `dumb_read_any(file, 0, 0)`.

Issue manifests slightly differently in DeaDBeeF that uses the DUMB plugin, version 1.0. The plugin says: "(C) 2009-2014, uses a fork of DUMB, Version 0.9.3". The issue here is: The file isn't recognized as a playable file at all. DeaDBeeF says: playlist load fail (basement.it)! failed to add file or folder basement.it.

File plays normally in VLC.

**Comment by kode54** [comment]
I have examined this file and determined it to be broken. The current version of DUMB will not even load it.

The 22nd sample, "U_WELCOM.XM", is truncated by 3871 bytes. All of the samples following it are completely missing.

I managed to find a copy of U_WELCOM.XM to replace that sample, which was a reversed version of the sample from the original module. But the filenames and sample names of the rest of the samples do not yield enough of a clue as to their origin, so they cannot be replaced.

**Comment by SimonN** [comment]
Thanks for the detailed analysis!

I was merely surprised that only DUMB rejected this file, and was worried whether DUMB had a bug, or the file. But if the file is as broken as you describe, then you're good in outright rejecting it.

It's just an unrelated bonus that VLC plays it somehow, not a bug in DUMB.

**Comment by kode54** [comment]
It would be a nice effort by somebody to try contacting Alexander Brandon and locate a working copy of that file, if it still exists.

**Comment by kode54** [comment]
Hey look, I have a present for you:

https://f.losno.co/basement.it.zip

Basically, basement.it and basement2.it use the same samples, so I just pasted the truncated sample data on from basement2.it, and it works. Enjoy.

**Comment by SimonN** [comment]
Hah, thanks! It's a beautiful piece.

Good to have this mystery cleared, even if it turns out that basement2 obsoletes basement1. I'll keep both!
