### ISSUE TITLE
Clean all whitespace

### ISSUE THREAD

**Issue by SimonN** [kode54/dumb#61]
The codebase has inconsistent indentation. Some parts use tabs, some parts use 4 spaces. Some files mix both wildly.

This is not urgent. Version 2.0 doesn't need consistent whitespace. But it's a nice guesture for future contributiors. Diffs will be cleaner, and pull requests will have a lower chance of stepping on each other.

For after 2.0, therefore, I propose:

* Choose a style of indentation: Tabs? 4 spaces? Something else?
* Choose someone to fix all whitespace in the codebase in one go:
    * Auto-convert to the preferred method of indentation.
    * Auto-prune all whitespace at end of lines.
* As suggested by Rondom below: Maybe add automation for contributors.

After this conversion, if future PRs would introduce weird whitespace, ask pull requesters to fix their whitespace before the merge.

My personal style is 4 spaces, but only 20 % of DUMB is in that style, 80 % of DUMB is tab-indented. For fun: [Tabs or spaces across repositories](https://ukupat.github.io/tabs-or-spaces/), where tabs, 2 spaces, and 4 spaces are almost equally popular across C projects.

**Comment by Rondom** [comment]
Maybe define a .clang-format based on the original formatting to keep it consistent in the future. That way one can use git clang-format to keep one's changed lines consistent with the style.

**Comment by kode54** [comment]
4 spaces is acceptable. Anyone want to take this one up? I can do it if nobody else wants to first.

**Comment by kode54** [comment]
Please suggest a .clang-format. I don't really know the format of the configuration file yet.

**Comment by kode54** [comment]
Never mind the file, I found what I need. This should be resolved by 15c9b0d47b302f09348e69c9b5d22e505d916909.

**Comment by SimonN** [comment]
Yep, looks great! And `git clang-format` will now both re-indent, and remove trailing whitespace.

Thanks!
