### ISSUE TITLE
0.9.3 -> 2.0 transition and 2.0 API shortcomings: document these

### ISSUE THREAD

**Issue by SimonN** [kode54/dumb#65]
You have your awesome DUMB 0.9.3 or DUMB 1.0 app, build it against DUMB 2.0, and everything crashes. What do you have to do?

Gist of the necessary doc:

* Build your DUMB-using project with warnings that show function pointer mismatches. Treat these warnings extremely carefully, most of them imply porting work.
* `DUMBFILE_SYSTEM` needs 7 pointers instead of 5, and the signatures have changed. Look in include/dumb.h for a quick overview, and in DUMBFILE_SYSTEM.md for a more complete spec.
* Some functions return `dumb_off_t` instead of `long`. Most of that is backwards compatible unless you have function pointers to these.

Shortcomings of the 2.0 API:

* `DUH.length` is `dumb_off_t`, but this is not the clearest type. It's good that this is 64-bit, but it doesn't measure disk file offsets. `length` measures the total time of the DUH in 65536-ths of a second, where a DUH is a format-agnostic abstraction of a tracked song.
* A sigrenderer is like a slider, or iterator, that moves along a DUH and decodes the music. The *position* of a sigrenderer is stored in `pos`, and this is exposed in the API as `long`. It should ideally have the same type as `DUH.length`.

What's the worst impact of these shortcomings? If your `long` is 32-bit (should only happen on Windows), your `pos` might be broken 2^15 seconds into a song, which is about 9 hours. It's really minimal impact, and this bug was already in DUMB 0.9.3. At best, it's sad that the 2.0 API isn't perfect. :-)

Thus, *don't* change anything in the 2.0 API. But let's point it out in the header, and document it in prose outside of the source.

(Ideally, for a theoretical 3.0 API in 5 years, both sigrenderer's `pos` and DUH's `length` should be of a new type `struct dumb_time_t { int32_t frac; int64_t seconds; }`, where the fractional part measures the 65536-ths of a second. Fixed-width integers. <3)

**Comment by kode54** [comment]
I think my newer timekeeping arrays make sure that the position is kept within the length of the song. Unfortunately, that could break if a real module is made that is greater than 9 hours long. Kind of a rare prospect, though.

**Comment by SimonN** [comment]
I'm closing this issue because you've written `UPDATING_YOUR_PROJECTS.md`; that file is easy to find. Thanks!
