### ISSUE TITLE
PSM Playback Has Garbled Sound

### ISSUE THREAD

**Issue by NewCreature** [kode54/dumb#71]
I have a few PSM modules in my collection and I noticed with DUMB 2.0 that these had garbled audio (they didn't with earlier versions). I found the issue was with a flags variable being used without being initialized. I've attached a patch that addresses the issue.

[old_psm_uninitialized_flags_fix.diff.zip](https://github.com/kode54/dumb/files/1366392/old_psm_uninitialized_flags_fix.diff.zip)

**Comment by kode54** [comment]
Thanks, fixed by 76ab0ba30b00f168ed421ecbae616e8e570c163f.
