### ISSUE TITLE
fb2k crashes while playing "ASIKWUSpulse - Shrubbing.s3m"

### ISSUE THREAD

**Issue by f2d** [kode54/dumb#89]
foo_dumb v2.0.3
foobar2000 v1.4 and 1.4.1

I'm not sure this is the right place to report this, but I'll try.

Foobar2000 always crashes during playback at the end of this file:
[ASIKWUSpulse - Shrubbing.s3m](https://modarchive.org/index.php?request=view_by_moduleid&query=184222)

I got the file from example songs distributed with OpenMPT editor, which plays it fine.
There seems to be some weird effect at the end, which prolongs a short sample to sound like a tape reel rolling to stop for some seconds. But what can be heard in fb2k at that place is several seconds of silence and then one short melodic "ping" sound right before crash.

Unrelated note: Skip Silence DSP jumps through the silent part quickly to the "ping", but does not cause or affect the crash.

Windows Error Report attached:
[Report.wer.txt](https://github.com/kode54/dumb/files/2716919/Report.wer.txt)

**Comment by kode54** [comment]
This is a problem in the st3play library, which is mostly not my own. For now, you may use the following workarounds:

1) Disable playptmod/modplay.
2) Install and use either foo_openmpt or foo_openmpt54 instead. I suggest the former for now, as I haven't updated the latter to new changes from upstream.

**Comment by f2d** [comment]
Now I noticed that the [foo_dumb component page](http://www.foobar2000.org/components/view/foo_dumb) says it's deprecated.

I removed foo_dumb and installed foo_openmpt, and now playback fully works, as far as I can see.

Thanks.
